dist: bionic
sudo: enabled

os:
  - linux

services:
  - docker

script:
  - docker-compose --version

jobs:
  include:
    - stage: build
      script: docker-compose build
    - stage: run
      script: docker-compose up
    - stage: test
      script: docker ps
    - stage: deploy
      script: docker-compose down