dist: bionic

services:
  - docker

before_install:
  - npm install eslint -g
  - eslint backend/

script:
  - docker image ls
  - docker-compose run backend tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/elasticsearch;
    fi