dist: bionic

language: nodejs

services:
  - docker

before_install:
  - cd backend/
  - npm install
  - eslint --version
  - eslint .
  - cd ..

script:
  - docker image ls
  - docker-compose run $DOCKERHUB_TOKEN/backend tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/moneymanager;
    fi