dist: bionic

os: linux
language: node_js
node_js:
  - "13"

sudo: required

services:
  - docker

before_install:
  - sudo apt update
  - sudo apt-get install node-legacy
  - cd backend/
  - npm install
  - npm run lint
  - cd ..

script:
  - docker-compose build
  - docker-compose run backend test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/moneyback;
    fi

notifications:
  email: false