dist: bionic

os: linux
language: node_js
node_js:
  - "10.16.0"

services:
  - docker

before_install:
  - cd backend/
  - npm i -g npm@^6.14.3
  - npm i -g node-gyp@latest && npm config set node_gyp "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js"
  - npm install
  - npm run lint
  - cd ..

script:
  - docker-compose build
  - docker-compose run backend test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/moneyback;
    fi

notifications:
  email: false