dist: bionic

os: linux
language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - cd backend/
  - npm install
  - npm i eslint-plugin-standard@latest --save-dev
  - npm i eslint-plugin-promise@latest --save-dev
  - eslint .
  - cd ..

script:
  - docker image ls
  - docker-compose run $DOCKERHUB_TOKEN/backend tests

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/moneyback;
    fi

notifications:
  email: false