dist: bionic
sudo: required

os: linux
language: node_js
node_js:
  - 13

services:
  - docker

before_install:
  - node -v
  - cd backend/
  - npm install
  - npm run lint
  - cd ..

script:
  - docker-compose build
  - docker-compose run silent

after_success:
  - sudo apt-get install apache2-utils
  - /bin/bash stress_testing.sh;
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKERHUB_TOKEN" -p="$DOCKERHUB_PASSWORD";
    docker push $DOCKERHUB_TOKEN/moneyback;
    fi

notifications:
  email: false
