version: "3.7"

services:
  postgres:
    image: postgres
    container_name: docker-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432

  backend:
    build:
      context: backend/
      args:
          PORT: ${NODE_PORT}
    command: test
    image: ${DOCKERHUB_TOKEN}/moneyback
    container_name: backend
    ports:
      - 8080:${NODE_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

volumes:
  db-data:
